# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v2
        
			- name: ssh setup
				env:
					SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

			- name: Some task that fetches dependencies
				env:
					SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          rsync -avz --delete openbsd-br.org/ deploybot@46.105.133.17:/var/www/openbsd-br.org/
