name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: ssh setup
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          apt-get update && apt-get install -y rsync openssh-client
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-keyscan 46.105.133.17 >> ~/.ssh/known_hosts
          ssh-keygen -R 46.105.133.17

      - name: Some task that fetches dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          rsync -avz --delete openbsd-br.org/ deploybot@46.105.133.17:/var/www/openbsd-br.org/
